# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - GO111MODULE=on go get github.com/golang/mock/mockgen@v1.4.4
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/helmes
    goos:
      - linux
      - windows
      - darwin
    binary: helmes
    ldflags:
    - -X "github.com/rugwirobaker/helmes.version={{ .Version }}"
    - -X "github.com/rugwirobaker/helmes.buildDate={{ .Env.DATE }}"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'